Repository DavidWellsTheDeveloper/cs414-f18-001-Team.name, pull requests merged in 2019-10, with the labels that each got.

#80 Create CreateDatabaseSchema.sql
  docs/CreateDatabaseSchema.sql
Labels: enhancement

#100 Hotfix to prevent selecting enemy pieces
  GameLogic/Game.java
  GameLogic/Move.java
Labels: bug, enhancement

#146 Added class diagram and CRC cards for gameLogic
  deliverables/design_artifacts/class_diagrams/GameLogic_refactor_class_diagram.jpg
  deliverables/design_artifacts/crc_diagrams/GameLogic CRC Cards.png
Labels: documentation
